### ISSUE TITLE
Slider does not trigger changes 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_choiceModels#12]
Numbers and arcs are the same, regardless of slider types/ position

**Comment by doorleyr** [comment]
Just checked this and its not currently updating because the cityIO grid API is down. @yasushisakai

**Comment by RELNO** [comment]
It was giving the same results for Volpe parcel while cityio still sent the grid.

**Comment by RELNO** [comment]
This is still the case as of today, Volpe Tract show the same results in any slider mode

**Comment by RELNO** [comment]
This is still an issue. Not sure how/if we can get realtime updates.

**Comment by RELNO** [comment]
closing for removal of slider function
