### ISSUE TITLE
https://cityio.media.mit.edu/choiceModels/ is off despite cityIO server restart 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_choiceModels#14]

**Comment by RELNO** [comment]
@yasushisakai could you please help on this?

**Comment by yasushisakai** [comment]
![error](https://user-images.githubusercontent.com/1502180/47312461-6bb76c00-d60a-11e8-97d9-3887ec7d37f4.png)

This is what I saw

**Comment by doorleyr** [comment]
The above didn't work because you're trying to run the python script directly rather than using the bash script (which makes sure you're in the right folder so that the relative file paths work properly). The bash script runCM.sh should also be run at startup. It's running now.

**Comment by yasushisakai** [comment]
Thanks!
