### ISSUE TITLE
cityIO table and fornt-end URLs are now called 'mocho' -> update py model accordingly 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_choiceModels#18]

**Comment by doorleyr** [comment]
Resolved in master but for some reason I couldn't update the version on the cityIO server. When I try to pull I get this:

error: insufficient permission for adding an object to repository database .git/objects

@yasushisakai  any ideas?

**Comment by yasushisakai** [comment]
sudo was needed to pull, running now, pls check   
  

  
  

  
  
>

**Comment by RELNO** [comment]
@doorleyr ca we close?

**Comment by yasushisakai** [comment]
closing, open if this is not the case 👾
