### ISSUE TITLE
process found with error?

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/CS_choiceModels#19]
![93993BE4-2319-4CC2-BA3D-9CB1C729D8D6](https://user-images.githubusercontent.com/1502180/54998393-689f1e00-4fa4-11e9-8036-5b6e2496afe0.jpeg)

I don’t know if this is an issue, but just reporting.

**Comment by yasushisakai** [comment]
leaving it as is please

```tmux -S /tmp/shared a -t choiceModels``` to see the error

**Comment by RELNO** [comment]
closing after discussion with @doorleyr
