### ISSUE TITLE
Declare NO-CORS in client options to avoid CORS error in FETCH api

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_choiceModels#3]
As discussed [here](https://github.com/CityScope/CS_CityIO_Backend/issues/37), API should be set to allow `CORS` for AJAX calls [GET, POST, etc] 
https://github.com/CityScope/CS_CityIO_Backend/issues/37#issuecomment-397286198

**Comment by yasushisakai** [comment]
@doorleyr  for your ref. https://flask-cors.readthedocs.io/en/latest/

**Comment by doorleyr** [comment]
I followed instructions in @yasushisakai link. Should be fixed now. Please test and let me know.

**Comment by RELNO** [comment]
fixed in https://github.com/CityScope/CS_choiceModels/commit/65288eb884969aae0274f6a7839a65d3948d44e9
