### ISSUE TITLE
geojson coordinate system :urn:ogc:def:crs:OGC:1.3:CRS84

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_choiceModels#4]
@doorleyr I am trying to parse the geojson file In GAMA and I get an error due to the coordiante system used. This is due to the library used GeoTools that is not compatible with this coordinate system (see https://osgeo-org.atlassian.net/browse/GEOT-1710 if you want to see it more in details)

So one question:

Is there a reason why you are using this coordinate system ```:urn:ogc:def:crs:OGC:1.3:CRS84```
if yes: what is the reason?
if no: would you be ok to change it to ```epsg:4326```

**Comment by doorleyr** [comment]
CRS84 is equivalent to EPSG:4326. I created the geojson by opening the official MassGIS shape file in QGIS and exporting it as geojson with the WGS84 coordinate system. There's no option for me to specify it as EPSG:4326 apart from changing the crs information in a text editor or something.

Is there some way you can tell Gama to treat it as EPSG:4326?

**Comment by agrignard** [comment]
ok for now I can easily change it by hand to EPSG:4326 (not the optimal solution but it's ok for now)

**Comment by nmtoken** [comment]
CRS84 is **NOT** equivalent to EPSG:4326

EPSG:4326 specifies coordinates in lat/long order and CRS:84 in long/lat order
