### ISSUE TITLE
Service is down 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_choiceModels#9]
at https://cityio.media.mit.edu/choiceModels/

**Comment by doorleyr** [comment]
Running again now. My tmux process had been killed so it looks like the whole server must have restarted. @yasushisakai is that correct? Shouldn't my bash script run on startup anyway?

**Comment by RELNO** [comment]
@doorleyr server was down y-day for a few, probably the cause. Closing, tnx.

**Comment by RELNO** [comment]
Down again -- TO DO: start service with cityIO service in same `.sh` command

**Comment by doorleyr** [comment]
Running now. @yasushisakai how do we handle the first TODO item?

**Comment by yasushisakai** [comment]
@doorleyr  I'll be testing this for the following hours, may cause multiple reboots
